### ISSUE TITLE
Error because of file encoding

### ISSUE THREAD

**Issue by gillesoorts** [WoLpH/django-admin-generator#15]
I get this error when starting a server after generating the admin.py file with admin generator:

SyntaxError: source code string cannot contain null bytes

It is caused by the encoding of the admin.py file. The file is encoded as UTF-16 LE, which seems to cause the error. The line at the top of the admin file doesn't seem to work:

# vim: set fileencoding=utf-8 :

**Comment by wolph** [comment]
That line at the top of the file is perhaps a bit silly in this case... I've removed it.

It depends on how you write the file but the windows terminals seem to have switched to `UTF-16 LE` by default lately. While I can easily remove the offending line, it won't fix your issue unfortunately because Python does not support UTF-16 LE files.

To illustrate:
```cmd
$ echo 'print("Hello World")' > test.py
$ python test.py
Hello World

# Now let's convert the file to UTF-16LE:

$ iconv -t UTF-16LE < test.py > test_utf_16.py
$ cat test_utf_16.py
print("Hello World")

$ python test_utf_16.py
Traceback (most recent call last):
  File "/Users/rick/Downloads/temp/test_utf_16.py", line 1, in <module>
    print("Hello World")
    ^
NameError: name 'p' is not defined
```

**Comment by gillesoorts** [comment]
Thanks for the information. 

The problem is indeed related to encoding in Windows. It go around the problem by converting a temporary file (called admin-generated.py) to utf-8 with an additional command:

powershell -command "Get-Content <<appname>>\admin-generated.py | Set-Content -Encoding utf8 <<appname>>\admin.py"
